# stage 1: build stage
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

# restore
COPY ["src/api/api.csproj", "api/"]
RUN dotnet restore "api/api.csproj"

# build
COPY ["src/api/", "api/"]
WORKDIR /src/api
RUN dotnet build "api.csproj" -c Release -o /app/build

# stage 2: publish stage
FROM build AS publish
RUN dotnet publish "api.csproj" -c Release -o /app/publish

# stage 3: run stage
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
ENV ASPNETCORE_HTTP_PORTS=5001
EXPOSE 5001
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "api.dll"]